# Generated by Django 3.1.7 on 2021-03-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0003_auto_20210320_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrevenue',
            name='date',
            field=models.PositiveIntegerField(default=1616864175, verbose_name='Datetime Unix'),
        ),
    ]
