# Generated by Django 3.1.7 on 2021-03-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0004_auto_20210327_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrevenue',
            name='date',
            field=models.PositiveIntegerField(default=1616864227, verbose_name='Datetime Unix'),
        ),
    ]
