# Generated by Django 3.1.7 on 2021-04-25 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0005_auto_20210327_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrevenue',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
