# Generated by Django 3.1.7 on 2021-04-17 16:33

from django.db import migrations
import django.utils.timezone
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210417_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
