# Generated by Django 3.1.7 on 2021-04-25 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_transaction_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
