# Generated by Django 3.1.7 on 2021-04-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('expected_date', models.PositiveIntegerField(max_length=32)),
                ('actual_date', models.PositiveIntegerField(max_length=32)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
