# Generated by Django 3.1.7 on 2021-04-17 16:37

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0003_auto_20210417_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicescall',
            name='actual_date',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0.0),
        ),
        migrations.AlterField(
            model_name='servicescall',
            name='expected_date',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0.0),
        ),
    ]
