# Generated by Django 3.1.7 on 2021-04-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0007_auto_20210419_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicescall',
            name='loss',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicescall',
            name='revenue',
            field=models.IntegerField(),
        ),
    ]
