# Generated by Django 3.1.7 on 2021-05-05 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0008_auto_20210425_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicescall',
            name='actual_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='servicescall',
            name='expected_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
